### ISSUE TITLE
Update documentation for building AIRPACT6

### ISSUE THREAD

**Issue by vonw** [wsular/airpact6#10]
The quarto documentation needs to be updated with the latest build information. 

- I need to make sure that the [CMAQ Tutorials](https://github.com/USEPA/CMAQ/blob/main/DOCS/Users_Guide/Tutorials/README.md) is cited
  - Especially these three links that have scripts to build CMAQ using gcc compilers
    - [netcdf libraries](https://github.com/USEPA/CMAQ/blob/main/DOCS/Users_Guide/Tutorials/gcc_install_netcdf_for_nc4_compression.csh)
    - [ioapi](https://github.com/USEPA/CMAQ/blob/main/DOCS/Users_Guide/Tutorials/gcc_install_ioapi_for_nc4_compression.csh)
    - [CMAQ v5.5](https://github.com/USEPA/CMAQ/blob/main/DOCS/Users_Guide/Tutorials/gcc_install_cmaq55_cb6r5_m3dry.csh)

- Note that these 3 scripts were combined into [gcc_install_lar.csh](https://github.com/wsular/airpact6/blob/main/dev/apptainer/gcc_install_lar.csh) for our custom installation.
  - This script will useful for building CMAQ in a container or on a virtual machine (VM).

**Comment by vonw** [comment]
Documentation is now up-to-date with current build using:

- gcc compilers, v9.5.0
- openmpi (v4.0.1)
- HDF5 (v1.10.5)
- netCDF C (v4.8.0)
- netCDF Fortran library (v4.5.3)
- netCDF CXX library (v4.3.1)

**Comment by Amin-2021** [comment]
So, I think these are the final compilers and libraries that we use for both CMAQ 5.5 and SMOKE 4.5. This is great that these are the same for CMAQ 5.5 and SMOKE 4.5.

gcc compilers, v9.5.0
openmpi (v4.0.1)
HDF5 (v1.10.5)
netCDF C (v4.8.0)
netCDF Fortran library (v4.5.3)
netCDF CXX library (v4.3.1)

I think we need to add the IOAPI v3.2 to this list as well.

I'm not sure why we need netCDF CXX library (v4.3.1). 

Also it seems we don't need to the netCDF parallel anymore (?).

**Comment by vonw** [comment]
> So, I think these are the final compilers and libraries that we use for both CMAQ 5.5 and SMOKE 4.5. This is great that these are the same for CMAQ 5.5 and SMOKE 4.5.
> gcc compilers, v9.5.0 openmpi (v4.0.1) HDF5 (v1.10.5) netCDF C (v4.8.0) netCDF Fortran library (v4.5.3) netCDF CXX library (v4.3.1)
> I think we need to add the IOAPI v3.2 to this list as well.
> I'm not sure why we need netCDF CXX library (v4.3.1).
> Also it seems we don't need to the netCDF parallel anymore (?).

@Amin-2021 You're correct on all of this.

- IOAPI-3.2 should be added to the list of libraries.
- I also don't think we need the netCDF CXX library. I included it because the csh scripts provided by the EPA for compiling CMAQv5.5 included this library. (It can easily be eliminated in future builds.)
- Parallel netCDF was always an option, so it isn't needed. Plus, it was not included as one of the libraries in the EPA csh scripts.
